config/routes.rb
RailsQuiz::Application.routes.draw do  
  root 'participants#index'

  resources :participants, only: [:index, :show]
  resources :drawings, only: [:index, :create]
end

app/models/drawing.rb
class Drawing < ActiveRecord::Base
	belongs_to :participant
end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/models/setting.rb
class Setting < ActiveRecord::Base
	def self.value(key)
		key = key.to_s
		val = Setting.find_by_key key
		if val.nil?
			Rails.logger.warn "Missing settings key: #{key}"
			""
		else
			val.value
		end
	end
	
	def self.true?(key)
		key = key.to_s
		value(key) == '1'
	end
	
	def self.set_value(key, value)
		key = key.to_s
		val = Setting.find_by_key key
		if val.nil?
			raise "Invalid setting key"
		else
			val.value = value
			val.save
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
	def index
		fetch_winners
	end

	def create
		winner_info = draw_winner

		fetch_winners

		respond_to do |format|
			format.html { render 'index' }
			format.js { render json: winner_info.to_json }
		end
	end

private

	def fetch_winners
		@drawings = Drawing.all.order('cycle desc, id desc')
	end

	# Draws a winner from the pool of participants using a raffle-style algorithm where each point counts as a "ticket" in a drawing.
	# A new drawing record is created and returned
	# Repeat winners are not allowed until everyone has won at least once
	#
	# TIP: Use drawing cycles to keep track of the current "round" of drawing.
	# 		 To update the drawing cycle, use: Setting.set_value('drawing_cycle', new_value)

	def draw_winner
		cycle = Setting.value('drawing_cycle').to_i

		ineligible_winner_ids = Drawing.where(cycle: cycle).map {|d| d.participant_id}
		ineligible_winner_ids = "" if ineligible_winner_ids.length == 0

		eligible_winners = Participant.where('id not in (?)', ineligible_winner_ids)

		if eligible_winners.length > 0
			point = 0
			all_points = eligible_winners.sum(:points)
			winning_point = rand(all_points)

			eligible_winners.each do |p|
				point += p.points
				if point >= winning_point
					drawing = Drawing.create(participant_id: p.id, cycle: cycle)

					return {
						name: p.name,
						points: p.points,
						drawing_id: drawing.id,
						cycle: cycle
					}
				end
			end

			return nil
		elsif Participant.count > 0
			logger.warn "Ran out of winners in this cycle"
			Setting.set_value('drawing_cycle', cycle + 1)

			return draw_winner
		else
			logger.warn "No eligible winners"

			return nil
		end
	end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	def index
		@participants = Participant.all.order('points desc')
	end

	def show
		@participant = Participant.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Rails Quiz</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	<link rel="shortcut icon" href="/favicon.ico">

	<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
	<![endif]-->

	<%= yield :head %>
</head>
<body>

<div class="container">

	<%= yield %>

</div>

</body>
</html>

app/views/participants/index.html.erb
<h3>Participants</h3>
<%= link_to "View Drawings", drawings_path, class: "btn btn-large btn-secondary" %>
<table class="table table-striped">	 
	 <thead>
			<tr>
				 <th>Name</th>
				 <th>Points</th>
			</tr>
	 </thead>
	 <tbody>
	 		<% @participants.each do |p| %>
			<tr>
				 <th><%= link_to p.name, p %></th>
				 <td><%= p.points %></td>
			</tr>
			<% end %>
	 </tbody>
</table>

app/views/participants/show.html.erb
<h3><%= @participant.name %></h3>
<%= link_to "Back", participants_path, class: "btn btn-large btn-secondary" %>
<table class="table table-striped">	 
	 <thead>
			<tr>
				 <th>Attribute</th>
				 <th>Value</th>
			</tr>
	 </thead>
	 <tbody>
			<tr>
				 <th>Name</th>
				 <td><%= @participant.name %></td>
			</tr>
			<tr>
				 <th>Points</th>
				 <td><%= @participant.points %></td>
			</tr>
			<tr>
				 <th>Won</th>
				 <td>??? times</td>
			</tr>
	 </tbody>
</table>